In [1]:
from langchain_openai import AzureChatOpenAI
from langchain.prompts import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    HumanMessagePromptTemplate,
)
import os

In [2]:
pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in /home/vscode/.local/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in /home/vscode/.local/lib/python3.10/site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [4]:
 
import pandas as pd 
  
df = pd.read_excel("step3result copy 2.xlsx") 
df

,Author 1: Relevant Article? (Yes/No),Author 2: Relevant Article? (Yes/No),month_published,title,keywords,abstract,PMID,medline_authors,URL,Downloaded,Text,APA_Citation,category
0,No,No,2021 Jun 3,Extra-axial haemorrhage in a patient with Alpo...,"['anaesthesia', 'pregnancy']",Extra-axial haemorrhage following epidural ana...,34083183,"['Wijayanayaka S', 'Guha A', 'Sivanesan K', 'V...",https://europepmc.org/backend/ptpmcrender.fcgi...,True,Case report\nExtra- axial haemorrhage in a pat...,"Wijayanayaka, S., Guha, A., Sivanesan, K., & V...",'Neurological Disorders'
1,No,No,2015 Mar,"Connective tissue, Ehlers-Danlos syndrome(s), ...","['POTS', 'cervical spine', 'connective tissue'...",Ehlers-Danlos syndrome (EDS) is an umbrella te...,25655119,"['Castori M', 'Morlino S', 'Ghibellini G', 'Ce...",https://europepmc.org/backend/ptpmcrender.fcgi...,True,Cheema et al. The Journal of Headache\nThe Jou...,"Castori, M., Morlino, S., Ghibellini, G., Cell...",'Neurological Disorders'
2,No,No,2018 Jan 18,Case 2-2018. A 41-Year-Old Woman with Vision D...,"['Adult', 'Diagnosis, Differential', 'Female',...",No abstract available,29342391,"['Cestari DM', 'Cunnane ME', 'Rizzo JF 3rd', '...",https://libkey.io/libraries/731/articles/17711...,False,"282 n engl j med 378;3 nejm.org January 18, 20...","Cestari, D. M., Cunnane, M. E., Rizzo III, J. ...",No abstract available
3,No,No,2016 Jun,[Safe and Effective Analgesia with Bilateral C...,"['Anesthesia, Epidural', 'Aortic Aneurysm, Abd...",A patient with Marfan syndrome underwent emerg...,27483660,"['Katakura Y', 'Sakurai A', 'Endo M', 'Hamada ...",https://europepmc.org/backend/ptpmcrender.fcgi...,True,TYPE CaseReport\nPUBLISHED 13March2023\nDOI 10...,"Katakura, Y., Sakurai, A., Endo, M., Hamada, T...",'Other Conditions'
4,No,No,2014 Sep,Joint hypermobility and headache: the glue tha...,"['Ehlers-Danlos syndrome', ""Marfan's syndrome""...",BACKGROUND: Past studies have reported that co...,24958300,"['Martin VT', 'Neilson D']",https://europepmc.org/backend/ptpmcrender.fcgi...,True,1212081\nresearch-article2023 GPHXXX10.1177/23...,"Martin, V. T., & Neilson, D. (2014). Joint hyp...",'Neurological Disorders'
5,No,No,1999 Jan-Feb,Progressive systemic sclerosis: intrathecal pa...,"['Aged', 'Analgesics, Opioid/*administration &...","BACKGROUND AND OBJECTIVES: At present, there i...",9952101,"['Lundborg CN', 'Nitescu PV', 'Appelgren LK', ...",Not available,False,Text not available,"Lundborg, C. N., Nitescu, P. V., Appelgren, L....",'Autoimmune Disorders'
6,No,No,2015 May,Marfan syndrome presenting with postpartum aor...,"['Adult', 'Aortic Dissection/complications/*di...",No abstract available,25790894,"['Humphrey V', 'Falzon D', 'Clark V']",https://libkey.io/libraries/731/articles/53923...,False,References 1. Auerbach M. IV Iron in pregnancy...,"Humphrey, V., Falzon, D., & Clark, V. (2015). ...",No abstract available
7,No,No,1948 Sep-Oct,[Injection of the sympathetic superior cervica...,['*ANESTHESIA AND ANESTHETICS/spinal--complica...,No abstract available,18893366,"['MOYSON F', 'LAMBIOTTE C']",Not available,False,Text not available,"MOYSON, F., & LAMBIOTTE, C. (1948). Injection ...",No abstract available
8,No,No,2015 Dec,SLE Neuropathy-Anything New?,"['Guillain-Barre Syndrome', 'Headache', 'Human...",SLE (systemic lupus erythematosus) is a multis...,27666897,['Londhey VA'],https://europepmc.org/backend/ptpmcrender.fcgi...,True,REVIEW\npublished:04July2022\ndoi:10.3389/fimm...,"Londhey, V. A. (2015). SLE Neuropathy-Anything...",'Neurological Disorders'
9,No,No,2021 May,Long-Term Safety and Efficacy of Anifrolumab i...,"['Adult', 'Antibodies, Antinuclear/immunology'...",OBJECTIVE: To investigate long-term safety and...,33225631,"['Chatham WW', 'Furie R', 'Saxena A', 'Brohawn...",https://europepmc.org/backend/ptpmcrender.fcgi...,True,"Arthritis & Rheumatology\nVol. 73, No. 5, May ...","Chatham, W. W., Furie, R., Saxena, A., Brohawn...",'Autoimmune Disorders'
10,No,No,2007 Summer,Topical review-connective tissue diseases: oro...,"['Arthritis, Rheumatoid/complications', 'Conne...",This topical review presents an overview of or...,17717956,"['Klasser GD', 'Balasubramaniam R', 'Epstein J']",https://europepmc.org/backend/ptpmcrender.fcgi...,True,diagnostics\nReview\nCurrent Perspectives on P...,"Klasser, G. O., Balasubramaniam, R., & Epstein...",'Autoimmune Disorders'
11,No,No,2024 Jan,Case 325.,"['Humans', 'Female', 'Aged', '*Deglutition Dis...",A 76-year-old woman with a history of rheumato...,38289217,"['Suthar PP', 'Nagarajan M', 'Bhabad S']",https://libkey.io/libraries/731/articles/60391...,False,DIAGNOSIS PLEASE • CASE 325 This copy is for p...,"Golfinos, J. G., Fitzpatrick, B. C., Smith, L....",'Neurological Disorders'
12,No,No,2018 Mar,Coexistence of antiphospholipid antibodies and...,"['Lupus anticoagulant', 'anti-beta2GPI antibod...",Background The occurrence of antiphospholipid ...,28952322,"['Islam MA', 'Alam F', 'Gan SH', 'Cavestro C',...",https://europepmc.org/backend/ptpmcrender.fcgi...,True,HHS Public Access\nAuthor manuscript\nCephalal...,"Islam, M. A., Alam, F., Gan, S. H., Cavestro, ...",'Autoimmune Disorders'
13,No,No,2021 Jun,Sleep Deficiency and Pediatric Chronic Pain.,"['Children', 'Chronic pain', 'Evaluation', 'FG...",Sleep deficiency in children is a public healt...,34023124,"['Zhai S', 'Phillips S', 'Ward TM']",Not available,False,Text not available,"Zhai, S., Phillips, S., & Ward, T. M. (2021). ...",'Other Conditions'
14,No,No,2014 Sep,Joint hypermobility and headache.,"['Ehlers-Danlos Syndrome/*complications', 'Hea...",No abstract available,25196367,['Tinkle BT'],https://europepmc.org/backend/ptpmcrender.fcgi...,True,NeurosurgicalReview(2019)42:915–936\nhttps://d...,"Neilson, D., & Martin, V. T. (2014). Joint hyp...",No abstract available
15,No,No,2023 Apr,Headache and systemic lupus erythematosus: A n...,"['autoimmune diseases', 'headache', 'migraine ...","OBJECTIVE: To review the epidemiology, the dif...",37036168,"['de Oliveira I', 'Sampaio Rocha-Filho PA']",https://europepmc.org/backend/ptpmcrender.fcgi...,True,Received:17September2023 Revised:12January2024...,"de Oliveira, I., & Sampaio Rocha‐Filho, P. A. ...",'Autoimmune Disorders'
16,No,No,2019 May,Intracranial hypertension in a patient with Cl...,"['Acetazolamide/*administration & dosage', 'An...",No abstract available,30995704,"['Chia XX', 'Cordato D', 'Venkat A', 'Spicer ST']",https://libkey.io/libraries/731/articles/29959...,False,Text not available,"Chia, X. X., Cordato, D., Venkat, A., & Spicer...",No abstract available

# GOAL: Take an abstract and assign it to one of three categories.

In [4]:
chat = AzureChatOpenAI(
    azure_endpoint="https://nlp-ai-svc.openai.azure.com/",
    openai_api_version="2023-06-01-preview",
    azure_deployment="ChatGPT4",
    openai_api_type="azure",
    temperature=0,
    model_name="gpt-4",
    api_key= os.environ.get("OPENAI_API_KEY")
)

In [5]:
from langchain.prompts import PromptTemplate

system_template = """ Help categorize the text file into either of the input categories given by the user and return 1 category as output."""


human_template = """
CONTEXT:
{context}

INPUT CATEGORIES:
{categories}

OUTPUT:
"""
system_message_prompt = SystemMessagePromptTemplate.from_template(system_template)
human_message_prompt = HumanMessagePromptTemplate.from_template(human_template)

In [6]:
categories = ["Neurological Disorders", "Autoimmune Disorders", "Renal Disorders", "Other Conditions"]

In [7]:
chat_prompt = ChatPromptTemplate.from_messages([system_message_prompt, human_message_prompt])

In [8]:
# folder_path = "data"
# output = []

# for filename in os.listdir(folder_path):
#     if filename.endswith(".txt"):  # Check if the file is a text file
#         file_path = os.path.join(folder_path, filename)
#         with open(file_path, 'r') as file:
#             print(file_path)
#             data = file.read()
#             result = chat.invoke(chat_prompt.format_prompt(categories=categories, context=data).to_messages())
#             output.append(result.content)

In [9]:
for index, row in df.iterrows():
    data = row['abstract']
    result = chat.invoke(chat_prompt.format_prompt(categories=categories, context=data).to_messages())
    df.at[index, 'category'] = result.content

In [10]:
print(df["category"])

0     'Neurological Disorders'
1       'Autoimmune Disorders'
2     'Neurological Disorders'
3           'Other Conditions'
4     'Neurological Disorders'
5     'Neurological Disorders'
6     'Neurological Disorders'
7     'Neurological Disorders'
8           'Other Conditions'
9     'Neurological Disorders'
10      'Autoimmune Disorders'
11          'Other Conditions'
12    'Neurological Disorders'
13          'Other Conditions'
14    'Neurological Disorders'
Name: category, dtype: object

In [11]:
df.to_excel('step2.xlsx', index=False)  # Set index=False to exclude the DataFrame index from the output

In [ ]:
# from langchain.text_splitter import CharacterTextSplitter


# # Create a RecursiveCharacterTextSplitter instance
# splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=200)

# splitter.create_documents([data])

In [12]:
df

,Author 1: Relevant Article? (Yes/No),Author 2: Relevant Article? (Yes/No),title,keywords,abstract,pmid,medline_authors,Full Text Link,AI Can Read Full Text?,category
0,No,No,Postdural Puncture Headache and Acute Subdural...,"['Acute subdural haematoma', ""Sjogren's syndro...",Although spontaneous intracranial hypotension ...,32076685,"['Yildirim HU', 'Bakir M', 'Atici SR']",a link will go here,Yes,'Neurological Disorders'
1,No,No,Idiopathic intracranial hypertension as the in...,"['Adolescent', 'Brain/pathology', 'Female', 'F...",A 14-year-old girl was referred for evaluation...,23376664,"['Rajasekharan C', 'Renjith SW', 'Marzook A', ...",a link will go here,Yes,'Autoimmune Disorders'
2,No,No,Case 325.,"['Humans', 'Female', 'Aged', '*Deglutition Dis...",A 76-year-old woman with a history of rheumato...,38289217,"['Suthar PP', 'Nagarajan M', 'Bhabad S']",a link will go here,Yes,'Neurological Disorders'
3,No,No,Intracranial hypertension in a patient with Cl...,"['Acetazolamide/*administration & dosage', 'An...",No abstract available,30995704,"['Chia XX', 'Cordato D', 'Venkat A', 'Spicer ST']",a link will go here,Yes,'Other Conditions'
4,No,No,[Characteristic manifestations of neuropsychia...,"['Adult', 'Female', 'Humans', 'Lupus Erythemat...",OBJECTIVE: To investigate the characteristic m...,16178450,"['Liu Z', 'Chen L', 'Cui LY']",a link will go here,Yes,'Neurological Disorders'
5,No,No,Parameters Related to Lumbar Puncture Do not A...,"['Headache', 'Lumbar puncture', 'Post-dural pu...",BACKGROUND: Post-dural puncture headache (PDPH...,31562971,"['Ljubisavljevic S', 'Trajkovic JZ', 'Ignjatov...",a link will go here,Yes,'Neurological Disorders'
6,No,No,Cerebrospinal fluid leaks secondary to dural t...,"['Cerebrospinal fluid leak', 'cerebrospinal fl...",OBJECTIVE: Damage to the dura mater often occu...,32242448,"['Gandhi J', 'DiMatteo A', 'Joshi G', 'Smith N...",a link will go here,Yes,'Neurological Disorders'
7,No,No,Intracranial hypotension with spinal pathology.,"['Humans', 'Intracranial Hypotension/diagnosis...",BACKGROUND CONTEXT: Intracranial hypotension (...,16934734,"['Inamasu J', 'Guiot BH']",a link will go here,Yes,'Neurological Disorders'
8,No,No,[Injection of the sympathetic superior cervica...,['*ANESTHESIA AND ANESTHETICS/spinal--complica...,No abstract available,18893366,"['MOYSON F', 'LAMBIOTTE C']",a link will go here,Yes,'Other Conditions'
9,No,No,Intracranial hypotension and hypertension in c...,['Brain Diseases/complications/*pathology/ther...,The specific aim of this review is to report t...,24880802,"['Ozge A', 'Bolay H']",a link will go here,Yes,'Neurological Disorders'
10,No,No,Progressive systemic sclerosis: intrathecal pa...,"['Aged', 'Analgesics, Opioid/*administration &...","BACKGROUND AND OBJECTIVES: At present, there i...",9952101,"['Lundborg CN', 'Nitescu PV', 'Appelgren LK', ...",a link will go here,Yes,'Autoimmune Disorders'
11,No,No,Case 2-2018. A 41-Year-Old Woman with Vision D...,"['Adult', 'Diagnosis, Differential', 'Female',...",No abstract available,29342391,"['Cestari DM', 'Cunnane ME', 'Rizzo JF 3rd', '...",a link will go here,Yes,'Other Conditions'
12,No,No,Intracranial hypertension in 2 children with m...,"['Amino Acid Substitution/genetics', 'Brain/pa...",Two unrelated children with Marfan syndrome pr...,18354149,"['Hilhorst-Hofstee Y', 'Kroft LJ', 'Pals G', '...",a link will go here,Yes,'Neurological Disorders'
13,No,No,An unusual cause of chronic headaches: question.,"['Arthritis, Rheumatoid/*complications/patholo...",No abstract available,25587612,"['Zuzuarregui JR', 'Lin J', 'Otis JA']",a link will go here,Yes,'Other Conditions'
14,No,No,Cerebral perfusion abnormalities in children w...,"['Adolescent', 'Antibodies, Anticardiolipin/an...",OBJECTIVE: Central nervous system (CNS) abnorm...,8014946,"['Szer IS', 'Miller JH', 'Rawlings D', 'Shaham...",a link will go here,Yes,'Neurological Disorders'